name: Build on ARM

on:
  # on each push and manual trigger
  push:
    branches: [ master ]
    paths-ignore: [ "**/Readme.md" ]
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu_latest
          - arch: armv7
            distro: ubuntu_latest

    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build binaries
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          install: |
            # ubuntu_latest is 24.04 as of 11-2024
            echo "OS:" $(uname -a)
            echo "   " $(lsb_release -d)
            echo

            apt update
            apt -y install fpc
            # Just get the -dev, instead of libtiff5 vs libtiff6 in some newer distros
            apt -y install libtiff-dev

          run: |
            echo "FPC:" $(fpc -iWTPTO)
            echo

            ./Scripts/compile.sh
            ./Scripts/tests-compile.sh

            cd Bin
            ls -lh ./

            ./tests -a -p --format=plain --no-addresses
            ./runtests.sh

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: deskew-binaries-${{ matrix.arch }}-${{ matrix.distro }}
          path: |
            Bin/deskew*
          if-no-files-found: error

      - name: Upload artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: deskew-artifacts-${{ matrix.arch }}-${{ matrix.distro }}
          path: |
            Bin
          if-no-files-found: error

