name: Build on ARM

on:
  # on each push and manual trigger
  push:
    branches: [ master ]
    paths-ignore: [ "**/Readme.md" ]
  workflow_dispatch:

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu22.04
          - arch: armv7
            distro: ubuntu22.04

    steps:
      - uses: actions/checkout@v4
      - uses: uraimo/run-on-arch-action@v2
        name: Build binaries
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}

          githubToken: ${{ github.token }}

          install: |
            echo "OS:" $(uname -a)
          
            apt-get update
            apt-get -y install fpc
            # ubuntu 22.04 is the last with libtiff5, newer have libtiff6
            apt-get -y install libtiff5

          run: |
            echo "FPC:" $(fpc -iWTPTO)            
            echo "OS:" $(uname -a)

            ./Scripts/compile.sh
            cd Bin
            ./runtests.sh --no-tiff

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: deskew-binaries-${{ matrix.arch }}-${{ matrix.distro }}
          path: |
            Bin/deskew*
          if-no-files-found: error

      - name: Upload artifacts
        if: github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v4
        with:
          name: deskew-artifacts-${{ matrix.arch }}-${{ matrix.distro }}
          path: |
            Bin
          if-no-files-found: error

